# Investor - Flow of Funds - US

### Introduction:

Special thanks to: https://github.com/rgrp for sharing the dataset.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv).

### Step 3. Assign it to a variable called

In [2]:
url = 'https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv'
df = pd.read_csv(url)
df.head()

,Date,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
0,2022-07-06,10167,NaN,3058,NaN,842,NaN,2216,NaN
1,2022-07-13,7409,NaN,2808,NaN,2067,NaN,741,NaN
2,2022-07-20,3468,NaN,102,NaN,-417,NaN,519,NaN
3,2022-07-27,14213,NaN,9667,NaN,8598,NaN,1069,NaN
4,2022-08-03,9786,NaN,4016,NaN,3079,NaN,937,NaN

### Step 4.  What is the frequency of the dataset?

In [3]:
df.columns

Index(['Date', 'Total Equity', 'Domestic Equity', 'World Equity', 'Hybrid',
       'Total Bond', 'Taxable Bond', 'Municipal Bond', 'Total'],
      dtype='str')

In [4]:
df['Date'] = pd.to_datetime(df['Date'])
df = df.set_index('Date')
pd.infer_freq(df.index)

In [5]:
df.index.dtype

dtype('<M8[us]')

In [6]:
df.index[:10]

DatetimeIndex(['2022-07-06', '2022-07-13', '2022-07-20', '2022-07-27',
               '2022-08-03', '2022-08-10', '2022-08-17', '2022-08-24',
               '2022-08-31', '2022-09-07'],
              dtype='datetime64[us]', name='Date', freq=None)

In [7]:
print(pd.infer_freq(df.index))

None

In [8]:
# pd.infer_freq() 回傳 None 的原因是資料裡某個地方有缺失的週，導致間隔不是完全規律的，
# pandas 的推斷邏輯很嚴格，只要有一個例外就放棄推斷。但這不代表頻率不存在，只代表資料不完整。

### Step 5. Set the column Date as the index.

### Step 6. What is the type of the index?

In [10]:
df.index.dtype

dtype('<M8[us]')

In [9]:
type(df.index)

pandas.DatetimeIndex

### Step 7. Set the index to a DatetimeIndex type

In [ ]:
# df.index = pd.DatetimeIndex(df.index)

### Step 8.  Change the frequency to monthly, sum the values and assign it to monthly.

In [19]:
monthly = df.resample('ME').sum(min_count=1)
monthly[:10]

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-31,35257.0,NaN,15635.0,NaN,11090.0,NaN,4545.0,NaN
2022-08-31,48596.0,NaN,32348.0,NaN,33705.0,NaN,-1357.0,NaN
2022-09-30,13775.0,NaN,10324.0,NaN,11629.0,NaN,-1305.0,NaN
2022-10-31,82879.0,NaN,55644.0,NaN,47435.0,NaN,8209.0,NaN
2022-11-30,82731.0,NaN,54314.0,NaN,37348.0,NaN,16967.0,NaN
2022-12-31,40451.0,NaN,29124.0,NaN,18273.0,NaN,10849.0,NaN
2023-01-31,34891.0,NaN,7849.0,NaN,-9996.0,NaN,17845.0,NaN
2023-02-28,13284.0,NaN,16508.0,NaN,6243.0,NaN,10264.0,NaN
2023-03-31,28856.0,NaN,3713.0,NaN,2500.0,NaN,1213.0,NaN
2023-04-30,39723.0,NaN,19058.0,NaN,14426.0,NaN,4632.0,NaN

### Step 9. You will notice that it filled the dataFrame with months that don't have any data with NaN. Let's drop these rows.

In [23]:
monthly_c = monthly.dropna(how='all')
monthly_c[:10]

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-31,35257.0,NaN,15635.0,NaN,11090.0,NaN,4545.0,NaN
2022-08-31,48596.0,NaN,32348.0,NaN,33705.0,NaN,-1357.0,NaN
2022-09-30,13775.0,NaN,10324.0,NaN,11629.0,NaN,-1305.0,NaN
2022-10-31,82879.0,NaN,55644.0,NaN,47435.0,NaN,8209.0,NaN
2022-11-30,82731.0,NaN,54314.0,NaN,37348.0,NaN,16967.0,NaN
2022-12-31,40451.0,NaN,29124.0,NaN,18273.0,NaN,10849.0,NaN
2023-01-31,34891.0,NaN,7849.0,NaN,-9996.0,NaN,17845.0,NaN
2023-02-28,13284.0,NaN,16508.0,NaN,6243.0,NaN,10264.0,NaN
2023-03-31,28856.0,NaN,3713.0,NaN,2500.0,NaN,1213.0,NaN
2023-04-30,39723.0,NaN,19058.0,NaN,14426.0,NaN,4632.0,NaN

### Step 10. Good, now we have the monthly data. Now change the frequency to year.

### BONUS: Create your own question and answer it.